/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unibague.poctiendainstrumentos.view;

import com.unibague.poctiendainstrumentos.model.Teclado;
import com.unibague.poctiendainstrumentos.service.IServicioInstrumento;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class GUIActualizarTeclado extends javax.swing.JFrame {
    
    private IServicioInstrumento servicioInstrumento;

    /**
     * Creates new form GUIActualizarTeclado
     */
    public GUIActualizarTeclado(IServicioInstrumento servicioInstrumento) {
        this.servicioInstrumento = servicioInstrumento;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        pnActualizarTeclado = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblNumTeclas = new javax.swing.JLabel();
        lbldigital = new javax.swing.JLabel();
        lblSensibilidad = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtNumTeclas = new javax.swing.JTextField();
        txtSensibilidad = new javax.swing.JTextField();
        txtDigitalAnalogico = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar teclado");
        setResizable(false);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar(evt);
            }
        });

        lblCodigo.setText("Código");

        lblNombre.setText("Nombre");

        lblMarca.setText("Marca");

        lblPrecio.setText("Precio");

        lblStock.setText("Stock");

        lblNumTeclas.setText("Numero de teclas");

        lbldigital.setText("Digital o analógico");

        lblSensibilidad.setText("Sensibilidad");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar(evt);
            }
        });

        javax.swing.GroupLayout pnActualizarTecladoLayout = new javax.swing.GroupLayout(pnActualizarTeclado);
        pnActualizarTeclado.setLayout(pnActualizarTecladoLayout);
        pnActualizarTecladoLayout.setHorizontalGroup(
            pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnActualizarTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombre)
                    .addComponent(lblMarca)
                    .addComponent(lblPrecio)
                    .addComponent(lblStock)
                    .addComponent(lblNumTeclas)
                    .addComponent(lblSensibilidad)
                    .addComponent(lbldigital))
                .addGap(40, 40, 40)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(txtMarca)
                    .addComponent(txtPrecio)
                    .addComponent(txtStock)
                    .addComponent(txtNumTeclas)
                    .addComponent(txtSensibilidad)
                    .addComponent(txtDigitalAnalogico)
                    .addGroup(pnActualizarTecladoLayout.createSequentialGroup()
                        .addComponent(txtCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        pnActualizarTecladoLayout.setVerticalGroup(
            pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnActualizarTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumTeclas))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldigital)
                    .addComponent(txtDigitalAnalogico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensibilidad))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar))
                    .addComponent(pnActualizarTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnActualizarTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnActualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar
        dispose();
    }//GEN-LAST:event_btnCerrar

    private void btnActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar
        if (txtCodigo.getText().isBlank() || txtNombre.getText().isBlank() || txtMarca.getText().isBlank() || txtPrecio.getText().isBlank()
                || txtStock.getText().isBlank() || txtNumTeclas.getText().isBlank() || txtDigitalAnalogico.getText().isBlank() || txtSensibilidad.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                
                Teclado teclado = new Teclado(txtCodigo.getText(), txtNombre.getText(), txtMarca.getText(), Double.parseDouble(txtPrecio.getText()),
                        Integer.parseInt(txtStock.getText()), Integer.parseInt(txtNumTeclas.getText()), txtCodigo.getText().equalsIgnoreCase("digital") ? true : false, txtSensibilidad.getText());
                servicioInstrumento.editarInstrumento(txtCodigo.getText(), teclado);
                JOptionPane.showMessageDialog(this, "Teclado actualizado correctamente");
                txtCodigo.setEditable(true);
                txtCodigo.setText("");
                txtNombre.setText("");
                txtMarca.setText("");
                txtPrecio.setText("");
                txtStock.setText("");
                txtNumTeclas.setText("");
                txtDigitalAnalogico.setText("");
                txtSensibilidad.setText("");
                
            } catch (RuntimeException e) {
                
                JOptionPane.showMessageDialog(this, "El precio, stock y numero de teclas debe ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnActualizar

    private void btnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar
        if (txtCodigo.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código del teclado a actualizar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            Teclado tecladoActualizar = (Teclado) servicioInstrumento.buscarInstrumento(txtCodigo.getText());
            if (tecladoActualizar != null) {
                txtCodigo.setEditable(false);
                txtNombre.setText(tecladoActualizar.getNombre());
                txtMarca.setText(tecladoActualizar.getMarca());
                txtPrecio.setText(Double.toString(tecladoActualizar.getPrecio()));
                txtStock.setText(Integer.toString(tecladoActualizar.getStock()));
                txtNumTeclas.setText(Integer.toString(tecladoActualizar.getNumeroTeclas()));
                txtDigitalAnalogico.setText(tecladoActualizar.isEsDigital() ? "Digital" : "Analogico");
                txtSensibilidad.setText(tecladoActualizar.getSensibilidad());
            } else {
                JOptionPane.showMessageDialog(this, "El teclado no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnBuscar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumTeclas;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSensibilidad;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lbldigital;
    private javax.swing.JPanel pnActualizarTeclado;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDigitalAnalogico;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumTeclas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSensibilidad;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
