/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unibague.poctiendainstrumentos.view;

import com.unibague.poctiendainstrumentos.model.Teclado;
import com.unibague.poctiendainstrumentos.service.IServicioInstrumento;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class GUIEliminarTeclado extends javax.swing.JFrame {

    private IServicioInstrumento servicioInstrumento;

    /**
     * Creates new form GUIEliminarTeclado
     */
    public GUIEliminarTeclado(IServicioInstrumento servicioInstrumento) {
        this.servicioInstrumento = servicioInstrumento;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnActualizarTeclado = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblNumTeclas = new javax.swing.JLabel();
        lbldigital = new javax.swing.JLabel();
        lblSensibilidad = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtNumTeclas = new javax.swing.JTextField();
        txtSensibilidad = new javax.swing.JTextField();
        txtDigitalAnalogico = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar teclado");
        setResizable(false);

        lblCodigo.setText("Código");

        lblNombre.setText("Nombre");

        lblMarca.setText("Marca");

        lblPrecio.setText("Precio");

        lblStock.setText("Stock");

        lblNumTeclas.setText("Numero de teclas");

        lbldigital.setText("Digital o analógico");

        lblSensibilidad.setText("Sensibilidad");

        txtNombre.setEditable(false);

        txtMarca.setEditable(false);

        txtPrecio.setEditable(false);

        txtStock.setEditable(false);

        txtNumTeclas.setEditable(false);

        txtSensibilidad.setEditable(false);

        txtDigitalAnalogico.setEditable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar(evt);
            }
        });

        javax.swing.GroupLayout pnActualizarTecladoLayout = new javax.swing.GroupLayout(pnActualizarTeclado);
        pnActualizarTeclado.setLayout(pnActualizarTecladoLayout);
        pnActualizarTecladoLayout.setHorizontalGroup(
            pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnActualizarTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNombre)
                    .addComponent(lblMarca)
                    .addComponent(lblPrecio)
                    .addComponent(lblStock)
                    .addComponent(lblNumTeclas)
                    .addComponent(lblSensibilidad)
                    .addComponent(lbldigital))
                .addGap(40, 40, 40)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(txtMarca)
                    .addComponent(txtPrecio)
                    .addComponent(txtStock)
                    .addComponent(txtNumTeclas)
                    .addComponent(txtSensibilidad)
                    .addGroup(pnActualizarTecladoLayout.createSequentialGroup()
                        .addComponent(txtCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(txtDigitalAnalogico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnActualizarTecladoLayout.setVerticalGroup(
            pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnActualizarTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumTeclas))
                .addGap(18, 18, 18)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldigital)
                    .addComponent(txtDigitalAnalogico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnActualizarTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSensibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSensibilidad))
                .addContainerGap())
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnActualizarTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnActualizarTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnBorrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar
        if (txtCodigo.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código del teclado a eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            Teclado tecladoBuscar = (Teclado) servicioInstrumento.buscarInstrumento(txtCodigo.getText());
            if (tecladoBuscar != null) {
                txtNombre.setText(tecladoBuscar.getNombre());
                txtMarca.setText(tecladoBuscar.getMarca());
                txtPrecio.setText(Double.toString(tecladoBuscar.getPrecio()));
                txtStock.setText(Integer.toString(tecladoBuscar.getStock()));
                txtNumTeclas.setText(Integer.toString(tecladoBuscar.getNumeroTeclas()));
                txtDigitalAnalogico.setText(tecladoBuscar.isEsDigital() ? "Digital" : "Analogico");
                txtSensibilidad.setText(tecladoBuscar.getSensibilidad());

            } else {
                JOptionPane.showMessageDialog(this, "El teclado no existe", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnBuscar

    private void btnCerrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrar

    private void btnBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar
        // TODO add your handling code here:
        int borrar = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas eliminar el teclado buscado?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (borrar == JOptionPane.YES_OPTION) {

            servicioInstrumento.eliminarInstrumento(txtCodigo.getText());
            txtCodigo.setText("");
            txtNombre.setText("");
            txtMarca.setText("");
            txtPrecio.setText("");
            txtStock.setText("");
            txtNumTeclas.setText("");
            txtDigitalAnalogico.setText("");
            txtSensibilidad.setText("");
            JOptionPane.showMessageDialog(null, "El teclado se ha borrado exitosamente");

        }
    }//GEN-LAST:event_btnBorrar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumTeclas;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSensibilidad;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lbldigital;
    private javax.swing.JPanel pnActualizarTeclado;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDigitalAnalogico;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumTeclas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSensibilidad;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
