package com.unibague.poctiendainstrumentos.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuInstrumento = new javax.swing.JMenu();
        jMenuListarGeneral = new javax.swing.JMenuItem();
        jMenuGuitarra = new javax.swing.JMenu();
        jMenuAddAccesorioGuitarra = new javax.swing.JMenuItem();
        jMenuDeleteAccesorioGuitarra = new javax.swing.JMenuItem();
        jMenuListarGuitarra = new javax.swing.JMenuItem();
        jMenuCrearGuitarra = new javax.swing.JMenuItem();
        jMenuBuscarGuitarra = new javax.swing.JMenuItem();
        jMenuEditarGuitarra = new javax.swing.JMenuItem();
        jMenuEliminarGuitarra = new javax.swing.JMenuItem();
        jMenuTeclado = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuAcercaDe = new javax.swing.JMenuItem();

        jMenuItem14.setText("jMenuItem14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda de Instrumentos");

        jMenuArchivo.setText("Archivo");

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalir(evt);
            }
        });
        jMenuArchivo.add(jMenuSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuInstrumento.setText("Instrumento");

        jMenuListarGeneral.setText("Listar");
        jMenuListarGeneral.setToolTipText("");
        jMenuListarGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarGeneral(evt);
            }
        });
        jMenuInstrumento.add(jMenuListarGeneral);

        jMenuGuitarra.setText("Guitarra");

        jMenuAddAccesorioGuitarra.setText("Agregar Accesorio");
        jMenuAddAccesorioGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddAccesorioGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuAddAccesorioGuitarra);

        jMenuDeleteAccesorioGuitarra.setText("Eliminar Accesorio");
        jMenuDeleteAccesorioGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeleteAccesorioGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuDeleteAccesorioGuitarra);

        jMenuListarGuitarra.setText("Listar");
        jMenuListarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuListarGuitarra);

        jMenuCrearGuitarra.setText("Crear ");
        jMenuCrearGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrearGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuCrearGuitarra);

        jMenuBuscarGuitarra.setText("Buscar");
        jMenuBuscarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuBuscarGuitarra);

        jMenuEditarGuitarra.setText("Editar");
        jMenuEditarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuEditarGuitarra);

        jMenuEliminarGuitarra.setText("Eliminar");
        jMenuEliminarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarGuitarra(evt);
            }
        });
        jMenuGuitarra.add(jMenuEliminarGuitarra);

        jMenuInstrumento.add(jMenuGuitarra);

        jMenuTeclado.setText("Teclado");

        jMenuItem6.setText("Guardar Preset");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSavePreset(evt);
            }
        });
        jMenuTeclado.add(jMenuItem6);

        jMenuItem7.setText("Cargar Preset");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoadPreset(evt);
            }
        });
        jMenuTeclado.add(jMenuItem7);

        jMenuItem11.setText("Listar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarTeclado(evt);
            }
        });
        jMenuTeclado.add(jMenuItem11);

        jMenuItem12.setText("Agregar");
        jMenuItem12.setToolTipText("");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarTeclado(evt);
            }
        });
        jMenuTeclado.add(jMenuItem12);

        jMenuItem13.setText("Buscar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarTeclado(evt);
            }
        });
        jMenuTeclado.add(jMenuItem13);

        jMenuItem15.setText("Actualizar");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActualizarTeclado(evt);
            }
        });
        jMenuTeclado.add(jMenuItem15);

        jMenuItem16.setText("Eliminar");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarTeclado(evt);
            }
        });
        jMenuTeclado.add(jMenuItem16);

        jMenuInstrumento.add(jMenuTeclado);

        jMenuBar1.add(jMenuInstrumento);

        jMenuAyuda.setText("Ayuda");

        jMenuAcercaDe.setText("Acerca de...");
        jMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcercaDe(evt);
            }
        });
        jMenuAyuda.add(jMenuAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenuAcercaDe(java.awt.event.ActionEvent evt) {                               
        JOptionPane.showMessageDialog(this, "Desarrollado por:\nGerman Castellanos\nJuan Lozano\nDavid Orjuela\nJorge Rodriguez");
    }                              

    private void jMenuListarGeneral(java.awt.event.ActionEvent evt) {                                    
        GUIListarGeneral gui = new GUIListarGeneral();
        gui.setVisible(true);
    }                                   

    private void jMenuAddAccesorioGuitarra(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
    }                                          

    private void jMenuBuscarGuitarra(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void jMenuSalir(java.awt.event.ActionEvent evt) {                            
        // TODO add your handling code here:
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        System.exit(0);
    }                           

    private void jMenuDeleteAccesorioGuitarra(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jMenuListarGuitarra(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void jMenuCrearGuitarra(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jMenuEditarGuitarra(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void jMenuEliminarGuitarra(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jMenuSavePreset(java.awt.event.ActionEvent evt) {                                 
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Preset guardado exitosamente");
    }                                

    private void jMenuLoadPreset(java.awt.event.ActionEvent evt) {                                 
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Preset cargado exitosamente");
    }                                

    private void jMenuListarTeclado(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        GUIListarTeclado gui = new GUIListarTeclado();
        gui.setVisible(true);
    }                                   

    private void jMenuAgregarTeclado(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        GUICrearTeclado gui = new GUICrearTeclado();
        gui.setVisible(true);
    }                                    

    private void jMenuBuscarTeclado(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        GUIBuscarTeclado gui = new GUIBuscarTeclado();
        gui.setVisible(true);
    }                                   

    private void jMenuActualizarTeclado(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        GUIActualizarTeclado gui = new GUIActualizarTeclado();
        gui.setVisible(true);
    }                                       

    private void jMenuEliminarTeclado(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        GUIEliminarTeclado gui = new GUIEliminarTeclado();
        gui.setVisible(true);
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem jMenuAcercaDe;
    private javax.swing.JMenuItem jMenuAddAccesorioGuitarra;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBuscarGuitarra;
    private javax.swing.JMenuItem jMenuCrearGuitarra;
    private javax.swing.JMenuItem jMenuDeleteAccesorioGuitarra;
    private javax.swing.JMenuItem jMenuEditarGuitarra;
    private javax.swing.JMenuItem jMenuEliminarGuitarra;
    private javax.swing.JMenu jMenuGuitarra;
    private javax.swing.JMenu jMenuInstrumento;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuListarGeneral;
    private javax.swing.JMenuItem jMenuListarGuitarra;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenu jMenuTeclado;
    // End of variables declaration                   
}
