/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unibague.poctiendainstrumentos.view;

import com.unibague.poctiendainstrumentos.service.IServicioInstrumento;
import com.unibague.poctiendainstrumentos.service.ServicioInstrumento;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());
    private IServicioInstrumento servicioInstrumento;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        this.servicioInstrumento = new ServicioInstrumento();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuInstrumento = new javax.swing.JMenu();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenuGuitarra = new javax.swing.JMenu();
        jMenuItemAgregarFunda = new javax.swing.JMenuItem();
        jMenuItemEliminarFunda = new javax.swing.JMenuItem();
        jMenuItemListarGuitarra = new javax.swing.JMenuItem();
        jMenuItemAgregarGuitarra = new javax.swing.JMenuItem();
        jMenuItemBuscarGuitarra = new javax.swing.JMenuItem();
        jMenuItemActualizarGuitarra = new javax.swing.JMenuItem();
        jMenuItemEliminarGuitarra = new javax.swing.JMenuItem();
        jMenuTeclado = new javax.swing.JMenu();
        jMenuItemGuardarPreset = new javax.swing.JMenuItem();
        jMenuItemCargaPreset = new javax.swing.JMenuItem();
        jMenuItemListarTeclado = new javax.swing.JMenuItem();
        jMenuItemAgregarTeclado = new javax.swing.JMenuItem();
        jMenuItemBuscarTeclado = new javax.swing.JMenuItem();
        jMenuItemActualizarTeclado = new javax.swing.JMenuItem();
        jMenuItemEliminarTeclado = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        jMenuItem14.setText("jMenuItem14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda de Instrumentos");
        setResizable(false);

        jMenuArchivo.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuInstrumento.setText("Instrumento");

        jMenuItemListar.setText("Listar");
        jMenuItemListar.setToolTipText("");
        jMenuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarActionPerformed(evt);
            }
        });
        jMenuInstrumento.add(jMenuItemListar);

        jMenuGuitarra.setText("Guitarra");

        jMenuItemAgregarFunda.setText("Agregar Funda");
        jMenuItemAgregarFunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarFundaActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemAgregarFunda);

        jMenuItemEliminarFunda.setText("Eliminar Funda");
        jMenuItemEliminarFunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarFundaActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemEliminarFunda);

        jMenuItemListarGuitarra.setText("Listar");
        jMenuItemListarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarGuitarraActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemListarGuitarra);

        jMenuItemAgregarGuitarra.setText("Agregar");
        jMenuItemAgregarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarGuitarraActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemAgregarGuitarra);

        jMenuItemBuscarGuitarra.setText("Buscar");
        jMenuItemBuscarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarGuitarraActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemBuscarGuitarra);

        jMenuItemActualizarGuitarra.setText("Actualizar");
        jMenuItemActualizarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarGuitarraActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemActualizarGuitarra);

        jMenuItemEliminarGuitarra.setText("Eliminar");
        jMenuItemEliminarGuitarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarGuitarraActionPerformed(evt);
            }
        });
        jMenuGuitarra.add(jMenuItemEliminarGuitarra);

        jMenuInstrumento.add(jMenuGuitarra);

        jMenuTeclado.setText("Teclado");

        jMenuItemGuardarPreset.setText("Guardar Preset");
        jMenuItemGuardarPreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarPresetActionPerformed(evt);
            }
        });
        jMenuTeclado.add(jMenuItemGuardarPreset);

        jMenuItemCargaPreset.setText("Cargar Preset");
        jMenuTeclado.add(jMenuItemCargaPreset);

        jMenuItemListarTeclado.setText("Listar");
        jMenuItemListarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarTecladoActionPerformed(evt);
            }
        });
        jMenuTeclado.add(jMenuItemListarTeclado);

        jMenuItemAgregarTeclado.setText("Agregar");
        jMenuItemAgregarTeclado.setToolTipText("");
        jMenuItemAgregarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarTecladoActionPerformed(evt);
            }
        });
        jMenuTeclado.add(jMenuItemAgregarTeclado);

        jMenuItemBuscarTeclado.setText("Buscar");
        jMenuItemBuscarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarTecladoActionPerformed(evt);
            }
        });
        jMenuTeclado.add(jMenuItemBuscarTeclado);

        jMenuItemActualizarTeclado.setText("Actualizar");
        jMenuItemActualizarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarTecladoActionPerformed(evt);
            }
        });
        jMenuTeclado.add(jMenuItemActualizarTeclado);

        jMenuItemEliminarTeclado.setText("Eliminar");
        jMenuItemEliminarTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarTecladoActionPerformed(evt);
            }
        });
        jMenuTeclado.add(jMenuItemEliminarTeclado);

        jMenuInstrumento.add(jMenuTeclado);

        jMenuBar1.add(jMenuInstrumento);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de...");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por:\nGerman Castellanos\nJuan Lozano\nDavid Orjuela\nJorge Rodriguez");
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarActionPerformed
        GUIListarGeneral gui = new GUIListarGeneral();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarActionPerformed

    private void jMenuItemAgregarFundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarFundaActionPerformed
        // TODO add your handling code here:
        GUIAgregarFunda gui = new GUIAgregarFunda();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarFundaActionPerformed

    private void jMenuItemBuscarGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarGuitarraActionPerformed
        // TODO add your handling code here:
        GUIBuscarGuitarra gui = new GUIBuscarGuitarra();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarGuitarraActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAgregarGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarGuitarraActionPerformed
        GUICrearGuitarra gui = new GUICrearGuitarra();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarGuitarraActionPerformed

    private void jMenuItemActualizarGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarGuitarraActionPerformed
        // TODO add your handling code here:
        GUIActualizarGuitarra gui = new GUIActualizarGuitarra();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarGuitarraActionPerformed

    private void jMenuItemEliminarGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarGuitarraActionPerformed
        // TODO add your handling code here:
        GUIEliminarGuitarra gui = new GUIEliminarGuitarra();
        gui.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemEliminarGuitarraActionPerformed

    private void jMenuItemEliminarFundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarFundaActionPerformed
        // TODO add your handling code here:
        GUIEliminarFunda gui = new GUIEliminarFunda();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarFundaActionPerformed

    private void jMenuItemListarGuitarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarGuitarraActionPerformed
        // TODO add your handling code here:
        GUIListarGuitarra gui = new GUIListarGuitarra();
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarGuitarraActionPerformed

    private void jMenuItemGuardarPresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarPresetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemGuardarPresetActionPerformed

    private void jMenuItemActualizarTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarTecladoActionPerformed
        // TODO add your handling code here:
        GUIActualizarTeclado gui = new GUIActualizarTeclado(servicioInstrumento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemActualizarTecladoActionPerformed

    private void jMenuItemBuscarTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarTecladoActionPerformed
        // TODO add your handling code here
        GUIBuscarTeclado gui = new GUIBuscarTeclado(servicioInstrumento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarTecladoActionPerformed

    private void jMenuItemAgregarTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarTecladoActionPerformed
        // TODO add your handling code here:
        GUICrearTeclado gui = new GUICrearTeclado(servicioInstrumento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarTecladoActionPerformed

    private void jMenuItemEliminarTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarTecladoActionPerformed
        // TODO add your handling code here:
        GUIEliminarTeclado gui = new GUIEliminarTeclado(servicioInstrumento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemEliminarTecladoActionPerformed

    private void jMenuItemListarTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarTecladoActionPerformed
        // TODO add your handling code here:
        GUIListarTeclado gui = new GUIListarTeclado(servicioInstrumento);
        gui.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarTecladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGuitarra;
    private javax.swing.JMenu jMenuInstrumento;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemActualizarGuitarra;
    private javax.swing.JMenuItem jMenuItemActualizarTeclado;
    private javax.swing.JMenuItem jMenuItemAgregarFunda;
    private javax.swing.JMenuItem jMenuItemAgregarGuitarra;
    private javax.swing.JMenuItem jMenuItemAgregarTeclado;
    private javax.swing.JMenuItem jMenuItemBuscarGuitarra;
    private javax.swing.JMenuItem jMenuItemBuscarTeclado;
    private javax.swing.JMenuItem jMenuItemCargaPreset;
    private javax.swing.JMenuItem jMenuItemEliminarFunda;
    private javax.swing.JMenuItem jMenuItemEliminarGuitarra;
    private javax.swing.JMenuItem jMenuItemEliminarTeclado;
    private javax.swing.JMenuItem jMenuItemGuardarPreset;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemListarGuitarra;
    private javax.swing.JMenuItem jMenuItemListarTeclado;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuTeclado;
    // End of variables declaration//GEN-END:variables
}
